eccube:
  rate_limiter:
    plg_customer_2fa_sms_send_onetime:
      # 実行するルーティングを指定します。
      route: plg_customer_2fa_sms_send_onetime
      # 実行するmethodを指定します。デフォルトはPOSTです。
      method: [ 'POST' ]
      # スロットリングの制御方法を設定します。ip・customerを指定できます。
      type: [ 'ip', 'customer' ]
      # 試行回数を設定します。
      limit: 30
      # インターバルを設定します。
      interval: '30 minutes'

parameters:
  env(PLUGIN_ECCUBE_2FA_SMS_ONE_TIME_TOKEN_LENGTH): '6'
  env(PLUGIN_ECCUBE_2FA_SMS_ONE_TIME_TOKEN_EXPIRE_AFTER_SECONDS): '300'

  plugin_eccube_2fa_sms_one_time_token_length: '%env(PLUGIN_ECCUBE_2FA_SMS_ONE_TIME_TOKEN_LENGTH)%'
  plugin_eccube_2fa_sms_one_time_token_expire_after_seconds: '%env(PLUGIN_ECCUBE_2FA_SMS_ONE_TIME_TOKEN_EXPIRE_AFTER_SECONDS)%'

