eccube:
  rate_limiter:
    sms_send_onetime_request:
      # 実行するルーティングを指定します。
      route: plg_customer_2fa_sms_send_onetime
      # 実行するmethodを指定します。デフォルトはPOSTです。
      method: [ 'POST' ]
      # スロットリングの制御方法を設定します。ip・customerを指定できます。
      type: [ 'ip', 'customer' ]
      # 試行回数を設定します。
      limit: 30
      # インターバルを設定します。
      interval: '30 minutes'
